Improves wallpaper setting workflow

diff --git a/home/.local/share/bin/set_wallpaper b/home/.local/share/bin/set_wallpaper
--- a/home/.local/share/bin/set_wallpaper
+++ b/home/.local/share/bin/set_wallpaper
@@ -1,28 +1,26 @@
 #!/usr/bin/env zsh
 
-found_dirs="All $(find ~/Pictures/wallpapers/* -maxdepth 0 -type d -printf '%f ')"
+if [[ -n "$1" ]]; then
+  image_path="$1"
+else
+  read -r image_path
+fi
 
-wallpaper_dirs=(`echo ${found_dirs}`)
+image_path=$(tr -d '\n' <<< "$image_path")
 
-selection=$(printf "%s\n" $wallpaper_dirs | fuzzel --dmenu --placeholder="Select Collection")
-
-[[ -z $selection ]] && exit 0
-
-[[ $selection = "All" ]] && selection=""
-
-selected=$(swiv -trofa "/home/javier/Pictures/wallpapers/$selection" | head -n 1)
-
-[[ -z $selected ]] && exit 0
+[[ -z $image_path ]] && echo "path required" && exit 1
+[[ ! -f $image_path ]] && echo "path is not a file" && exit 1
 
 config="/home/javier/.config/hypr/hyprpaper.conf"
 
-echo "\$wallpaper = $selected" > $config
+echo "\$wallpaper = $image_path" > $config
 echo "preload = \$wallpaper" >> $config
 echo "wallpaper = , \$wallpaper" >> $config
 
-hyprctl hyprpaper unload all
+hyprctl -q hyprpaper unload all 
 killall hyprpaper
 
-hyprpaper &
+hyprpaper > /dev/null 2>&1 &
+disown
 
 notify-send "Wallpaper Changed!"
